import {
  Button,
  Card,
  CardActions,
  CardContent,
  CardMedia,
  Grid,
  Typography,
} from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { ProductsTypes } from "@/types/UserInterface";
import AccessAlarmIcon from "@mui/icons-material/AccessAlarm";
import PhotoLibraryOutlinedIcon from "@mui/icons-material/PhotoLibraryOutlined";
import ArrowForwardIosIcon from "@mui/icons-material/ArrowForwardIos";
import Link from "next/link";
import { Carousel } from "react-bootstrap";

const testimonies = [
  {
    name: "Regina Miles",
    occupation: "Designer",
    testimony:
      "Slate helps you see how many more days you need to work to reach your financial goal.",
    imgPath: "/img/user-one.jpg",
  },
  {
    name: "Daniel Bird",
    occupation: "Doctor",
    testimony: "I love this website, it is built with precision.",
    imgPath: "/img/user-two.png",
  },
  {
    name: "Bali Kataga",
    occupation: "Engineer",
    testimony:
      "Next basket is a great company, I love the ideas and solution they provide to the world.",
    imgPath: "/img/user-three.png",
  },
];

export default function Home({ products }: any) {
  //STATES
  const [viewMoreProducts, setViewMoreProducts] = useState(false);

  return (
    <>
      <Head>
        <title>Bandage | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/logo.jpg" />
      </Head>
      <main className="main">
        <section className="furniture">
          <div className="furniture-container">
            <div className="plates">
              <Image
                src="/img/plates.png"
                alt="plates"
                width={452}
                height={616}
              />
            </div>
            <div className="vase-cups">
              <div className="vase">
                <Image
                  src="/img/vase.png"
                  alt="vase"
                  width={690}
                  height={300}
                />
              </div>
              <div className="light-cup">
                <div className="lights">
                  <Image
                    src="/img/light.png"
                    alt="lights"
                    width={330}
                    height={300}
                  />
                </div>
                <div className="cups">
                  <Image
                    src="/img/cups.png"
                    alt="cups"
                    width={330}
                    height={300}
                  />
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="products">
          <div className="product-header">
            <Typography align="center" variant="h5" fontFamily="Montserrat">
              Featured Products
            </Typography>
            <Typography
              align="center"
              variant="h4"
              color="#252B42"
              fontWeight="700"
              fontFamily="Montserrat"
            >
              BESTSELLER PRODUCTS
            </Typography>
            <Typography align="center" variant="body2" fontFamily="Montserrat">
              Problems trying to resolve the conflict between
            </Typography>
          </div>

          <Grid container spacing={2} rowSpacing={3}>
            {products
              .slice(0, 12)
              .map(
                ({
                  thumbnail,
                  title,
                  id,
                  price,
                  category,
                  discountPercentage,
                }: ProductsTypes) => (
                  <Grid item key={id} xs={12} md={2}>
                    <Card sx={{ maxWidth: 183, height: "max-content" }}>
                      <Link href={`/products/${id}`}>
                        <CardMedia
                          component="img"
                          height="238"
                          image={thumbnail}
                          alt={title}
                        />
                        <CardContent>
                          <div className="card-title">
                            <Typography
                              gutterBottom
                              align="center"
                              variant="body2"
                              color="#252B42"
                              fontWeight="700"
                              fontFamily="Montserrat"
                              fontSize={10}
                            >
                              {title}
                            </Typography>
                          </div>
                          <Typography
                            gutterBottom
                            align="center"
                            variant="body2"
                            fontWeight="600"
                            fontFamily="Montserrat"
                            fontSize={10}
                          >
                            {category}
                          </Typography>
                          <div className="prices">
                            <Typography
                              gutterBottom
                              align="center"
                              variant="body2"
                              fontWeight="600"
                              fontFamily="Montserrat"
                              fontSize={10}
                              color="#BDBDBD"
                            >
                              ${price}
                            </Typography>
                            <Typography
                              gutterBottom
                              align="center"
                              variant="body2"
                              fontWeight="600"
                              fontFamily="Montserrat"
                              fontSize={10}
                              color="#23856D"
                            >
                              $
                              {Math.trunc(
                                price - (price / 100) * discountPercentage
                              )}
                            </Typography>
                          </div>
                        </CardContent>
                      </Link>
                    </Card>
                  </Grid>
                )
              )}
          </Grid>
          {viewMoreProducts ? (
            <Grid container spacing={2} rowSpacing={3} marginTop={1}>
              {products
                .slice(12, 30)
                .map(
                  ({
                    thumbnail,
                    title,
                    id,
                    price,
                    category,
                    discountPercentage,
                  }: ProductsTypes) => (
                    <Grid item key={id} xs={12} md={2}>
                      <Card sx={{ maxWidth: 183 }}>
                        <Link href={`/products/${id}`}>
                          <CardMedia
                            component="img"
                            height="238"
                            image={thumbnail}
                            alt={title}
                          />
                          <div>
                            <CardContent>
                              <div className="card-title">
                                <Typography
                                  gutterBottom
                                  align="center"
                                  variant="body2"
                                  color="#252B42"
                                  fontWeight="700"
                                  fontFamily="Montserrat"
                                  fontSize={10}
                                >
                                  {title}
                                </Typography>
                              </div>
                              <Typography
                                gutterBottom
                                align="center"
                                variant="body2"
                                fontWeight="600"
                                fontFamily="Montserrat"
                                fontSize={10}
                              >
                                {category}
                              </Typography>
                              <div className="prices">
                                <Typography
                                  gutterBottom
                                  align="center"
                                  variant="body2"
                                  fontWeight="600"
                                  fontFamily="Montserrat"
                                  fontSize={10}
                                  color="#BDBDBD"
                                >
                                  ${price}
                                </Typography>
                                <Typography
                                  gutterBottom
                                  align="center"
                                  variant="body2"
                                  fontWeight="600"
                                  fontFamily="Montserrat"
                                  fontSize={10}
                                  color="#23856D"
                                >
                                  $
                                  {Math.trunc(
                                    price - (price / 100) * discountPercentage
                                  )}
                                </Typography>
                              </div>
                            </CardContent>
                          </div>
                        </Link>
                      </Card>
                    </Grid>
                  )
                )}
            </Grid>
          ) : (
            <div className="load-more-button">
              <Button
                onClick={() => setViewMoreProducts(true)}
                variant="outlined"
              >
                LOAD MORE PRODUCTS
              </Button>
            </div>
          )}
        </section>
        <section className="services">
          <div className="product-header">
            <Typography align="center" variant="h5" fontFamily="Montserrat">
              Featured Products
            </Typography>
            <Typography
              align="center"
              variant="h4"
              color="#252B42"
              fontWeight="700"
              fontFamily="Montserrat"
            >
              THE BEST SERVICES
            </Typography>
            <Typography align="center" variant="body2" fontFamily="Montserrat">
              Problems trying to resolve the conflict between
            </Typography>
          </div>

          <Grid container spacing={2}>
            <Grid item xs={12} md={4}>
              <div className="service-card">
                <Image
                  src="/img/book-reader.png"
                  alt="plates"
                  width={72}
                  height={72}
                />
                <Typography
                  align="center"
                  variant="h4"
                  color="#252B42"
                  fontWeight="700"
                  fontFamily="Montserrat"
                >
                  Easy Wins
                </Typography>
                <Typography
                  align="center"
                  variant="body2"
                  fontFamily="Montserrat"
                >
                  Get your best looking smile now!
                </Typography>
              </div>
            </Grid>
            <Grid item xs={12} md={4}>
              <div className="service-card">
                <Image
                  src="/img/carbon-book.png"
                  alt="plates"
                  width={72}
                  height={72}
                />
                <Typography
                  align="center"
                  variant="h4"
                  color="#252B42"
                  fontWeight="700"
                  fontFamily="Montserrat"
                >
                  Concrete
                </Typography>
                <Typography
                  align="center"
                  variant="body2"
                  fontFamily="Montserrat"
                >
                  Defalcate is most focused in helping you discover your most
                  beautiful smile
                </Typography>
              </div>
            </Grid>
            <Grid item xs={12} md={4}>
              <div className="service-card">
                <Image
                  src="/img/growth-curve.png"
                  alt="plates"
                  width={72}
                  height={72}
                />
                <Typography
                  align="center"
                  variant="h4"
                  color="#252B42"
                  fontWeight="700"
                  fontFamily="Montserrat"
                >
                  Hack Growth
                </Typography>
                <Typography
                  align="center"
                  variant="body2"
                  fontFamily="Montserrat"
                >
                  Overcame any hurdle or any other problem.
                </Typography>
              </div>
            </Grid>
          </Grid>
        </section>
        <section className="posts">
          <div className="product-header">
            <Typography
              align="center"
              variant="body2"
              fontFamily="Montserrat"
              color="#23A6F0"
              fontWeight="700"
            >
              Practice Advice
            </Typography>
            <Typography
              align="center"
              variant="h3"
              color="#252B42"
              fontWeight="700"
              fontFamily="Montserrat"
            >
              Featured Posts
            </Typography>
          </div>
          <Grid container spacing={2}>
            <Grid item xs={12} md={4}>
              <Card sx={{ maxWidth: 345 }}>
                <CardMedia
                  component="img"
                  alt="posts"
                  height="300"
                  image="/img/post-one.png"
                />
                <CardContent>
                  <div className="post-cat">
                    <Typography
                      variant="body2"
                      fontFamily="Montserrat"
                      fontSize="11px"
                    >
                      Google
                    </Typography>
                    <Typography
                      variant="body2"
                      fontFamily="Montserrat"
                      fontSize="11px"
                    >
                      Trending
                    </Typography>
                    <Typography
                      variant="body2"
                      fontFamily="Montserrat"
                      fontSize="11px"
                    >
                      New
                    </Typography>
                  </div>
                  <Typography
                    variant="body2"
                    fontFamily="Montserrat"
                    fontSize="18px"
                    color="#252B42"
                    marginTop="1em"
                  >
                    Loudest à la Madison #1
                  </Typography>
                  <Typography
                    variant="body2"
                    fontFamily="Montserrat"
                    fontSize="18px"
                    color="#252B42"
                  >
                    (L&lsquo;integral)
                  </Typography>
                  <Typography
                    variant="body2"
                    color="text.secondary"
                    marginTop="1em"
                  >
                    We focus on ergonomics and meeting you where you work.
                    It&lsquo;s only a keystroke away.
                  </Typography>
                  <div className="post-date">
                    <div className="date">
                      <AccessAlarmIcon fontSize="small" className="date-icon" />
                      <Typography
                        variant="body2"
                        fontFamily="Montserrat"
                        fontSize="11px"
                      >
                        22 April 2021
                      </Typography>
                    </div>
                    <div className="date">
                      <PhotoLibraryOutlinedIcon
                        fontSize="small"
                        className="comment-icon"
                      />
                      <Typography
                        variant="body2"
                        fontFamily="Montserrat"
                        fontSize="11px"
                      >
                        10 comments
                      </Typography>
                    </div>
                  </div>
                </CardContent>
                <CardActions>
                  <Button size="small" endIcon={<ArrowForwardIosIcon />}>
                    Learn More
                  </Button>
                </CardActions>
              </Card>
            </Grid>
            <Grid item xs={12} md={4}>
              <Card sx={{ maxWidth: 345 }}>
                <CardMedia
                  component="img"
                  alt="posts"
                  height="300"
                  image="/img/post-two.png"
                />
                <CardContent>
                  <div className="post-cat">
                    <Typography
                      variant="body2"
                      fontFamily="Montserrat"
                      fontSize="11px"
                    >
                      Google
                    </Typography>
                    <Typography
                      variant="body2"
                      fontFamily="Montserrat"
                      fontSize="11px"
                    >
                      Trending
                    </Typography>
                    <Typography
                      variant="body2"
                      fontFamily="Montserrat"
                      fontSize="11px"
                    >
                      New
                    </Typography>
                  </div>
                  <Typography
                    variant="body2"
                    fontFamily="Montserrat"
                    fontSize="18px"
                    color="#252B42"
                    marginTop="1em"
                  >
                    Loudest à la Madison #1
                  </Typography>
                  <Typography
                    variant="body2"
                    fontFamily="Montserrat"
                    fontSize="18px"
                    color="#252B42"
                  >
                    (L&lsquo;integral)
                  </Typography>
                  <Typography
                    variant="body2"
                    color="text.secondary"
                    marginTop="1em"
                  >
                    We focus on ergonomics and meeting you where you work.
                    It&lsquo;s only a keystroke away.
                  </Typography>
                  <div className="post-date">
                    <div className="date">
                      <AccessAlarmIcon fontSize="small" className="date-icon" />
                      <Typography
                        variant="body2"
                        fontFamily="Montserrat"
                        fontSize="11px"
                      >
                        22 April 2021
                      </Typography>
                    </div>
                    <div className="date">
                      <PhotoLibraryOutlinedIcon
                        fontSize="small"
                        className="comment-icon"
                      />
                      <Typography
                        variant="body2"
                        fontFamily="Montserrat"
                        fontSize="11px"
                      >
                        10 comments
                      </Typography>
                    </div>
                  </div>
                </CardContent>
                <CardActions>
                  <Button size="small" endIcon={<ArrowForwardIosIcon />}>
                    Learn More
                  </Button>
                </CardActions>
              </Card>
            </Grid>
            <Grid item xs={12} md={4}>
              <Card sx={{ maxWidth: 345 }}>
                <CardMedia
                  component="img"
                  alt="posts"
                  height="300"
                  image="/img/post-three.png"
                />
                <CardContent>
                  <div className="post-cat">
                    <Typography
                      variant="body2"
                      fontFamily="Montserrat"
                      fontSize="11px"
                    >
                      Google
                    </Typography>
                    <Typography
                      variant="body2"
                      fontFamily="Montserrat"
                      fontSize="11px"
                    >
                      Trending
                    </Typography>
                    <Typography
                      variant="body2"
                      fontFamily="Montserrat"
                      fontSize="11px"
                    >
                      New
                    </Typography>
                  </div>
                  <Typography
                    variant="body2"
                    fontFamily="Montserrat"
                    fontSize="18px"
                    color="#252B42"
                    marginTop="1em"
                  >
                    Loudest à la Madison #1
                  </Typography>
                  <Typography
                    variant="body2"
                    fontFamily="Montserrat"
                    fontSize="18px"
                    color="#252B42"
                  >
                    (L&lsquo;integral)
                  </Typography>
                  <Typography
                    variant="body2"
                    color="text.secondary"
                    marginTop="1em"
                  >
                    We focus on ergonomics and meeting you where you work.
                    It&lsquo;s only a keystroke away.
                  </Typography>
                  <div className="post-date">
                    <div className="date">
                      <AccessAlarmIcon fontSize="small" className="date-icon" />
                      <Typography
                        variant="body2"
                        fontFamily="Montserrat"
                        fontSize="11px"
                      >
                        22 April 2021
                      </Typography>
                    </div>
                    <div className="date">
                      <PhotoLibraryOutlinedIcon
                        fontSize="small"
                        className="comment-icon"
                      />
                      <Typography
                        variant="body2"
                        fontFamily="Montserrat"
                        fontSize="11px"
                      >
                        10 comments
                      </Typography>
                    </div>
                  </div>
                </CardContent>
                <CardActions>
                  <Button size="small" endIcon={<ArrowForwardIosIcon />}>
                    Learn More
                  </Button>
                </CardActions>
              </Card>
            </Grid>
          </Grid>
        </section>
        <section className="testimonies">
          <div className="testimonies-container">
            <div className="testimony">
              <Typography
                gutterBottom
                align="center"
                variant="h4"
                color="#252B42"
                fontWeight="700"
                fontFamily="Montserrat"
              >
                What they say about us
              </Typography>
              <div className="user-testimony">
                <Carousel
                  bsPrefix="carousel"
                  slide={true}
                  interval={1500}
                  className="carousel"
                >
                  {testimonies.map((testimony: any) => (
                    <Carousel.Item
                      className="carousel-container"
                      key={testimony.name}
                    >
                      <div className="testimony-container">
                        <Image
                          src={testimony.imgPath}
                          alt="user"
                          width={90}
                          height={90}
                          className="testimony-user"
                        />
                        <Image
                          src="/img/stars.png"
                          alt="rating"
                          width={132}
                          height={22}
                          className="testimony-user"
                        />
                        <Typography
                          align="center"
                          variant="body2"
                          fontFamily="Montserrat"
                        >
                          {testimony.testimony}
                        </Typography>
                        <Typography
                          align="center"
                          variant="h6"
                          color="#23A6F0"
                          fontWeight="700"
                          fontFamily="Montserrat"
                          fontSize={14}
                          marginTop="1em"
                        >
                          {testimony.name}
                        </Typography>
                        <Typography
                          align="center"
                          variant="body2"
                          fontWeight="700"
                          fontFamily="Montserrat"
                          fontSize={14}
                          marginTop="-1.5em"
                        >
                          {testimony.occupation}
                        </Typography>
                      </div>
                    </Carousel.Item>
                  ))}
                </Carousel>
              </div>
            </div>
            <div className="test-photo">
              <Image
                src="/img/users-group.png"
                alt="users"
                width={464}
                height={426}
              />
            </div>
          </div>
        </section>
        <section className="design-advert">
          <div className="advert">
            <Typography
              align="center"
              variant="h6"
              color="#23A6F0"
              fontWeight="700"
              fontFamily="Montserrat"
              fontSize={14}
            >
              Designing Better Experience
            </Typography>
            <Typography
              align="center"
              variant="h3"
              color="#252B42"
              fontWeight="700"
              fontFamily="Montserrat"
              marginTop="1em"
            >
              Problems trying to resolve the conflict between
            </Typography>
            <div className="paragraph">
              <Typography
                align="center"
                variant="body2"
                color="#252B42"
                fontFamily="Montserrat"
                marginTop="2em"
              >
                Problems trying to resolve the conflict between the two major
                realms of Classical physics:
              </Typography>
            </div>
            <Typography
              align="center"
              variant="h4"
              color="#23856D"
              fontWeight="700"
              fontFamily="Montserrat"
              marginTop="0.7em"
            >
              $16.48
            </Typography>
            <Button
              variant="contained"
              sx={{ backgroundColor: "#23A6F0", marginTop: "2em" }}
            >
              ADD YOUR CALL TO ACTION
            </Button>
          </div>
        </section>
        <div className="footer-pad"></div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  let allProducts = [];
  try {
    const productsResponse = await fetch("https://dummyjson.com/products");
    const products = await productsResponse.json();

    if (products) {
      allProducts = products;
    }
    // Use the data as needed
  } catch (error) {
    console.error(error);

    if (error) {
      allProducts = [];
    }
  }

  return {
    props: {
      products: allProducts.products,
    },
  };
}
